import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  Image,
  ScrollView,
  ImageBackground,
  SafeAreaView,
} from 'react-native';
import SimpleHeader from './common/headers/SimpleHeader';
import LoadingPopup from './common/popups/LoadingPopup';
interface IProps {
  isLoading: boolean;
}

const Legal = (props: IProps) => {
  return (
    <SafeAreaView style={styles.container}>
      {/* <LoadingPopup isVisible={props.isLoading} /> */}
      <ImageBackground
        resizeMode="stretch"
        style={{
          flex: 1,
        }}
        source={require('../assets/images/common/appBackground.webp')}>
        {/* <SimpleHeader
          showSettingsIcon={false}
          title="Voice"
          onMenuPressed={props.onMenuPressed}
        /> */}
        <View style={styles.container}>
          <ScrollView contentContainerStyle={styles.scrollContainer}>
            <View style={styles.iconContainer}>
              <Image
                source={require('../assets/images/legalImage.png')}
                style={styles.icon}
              />
              <Text style={styles.title}>Legal</Text>
            </View>

            <View style={styles.card}>
              <Text style={styles.cardTitle}>Legal Disclaimer</Text>
              <Text style={styles.cardContent}>
                MedSightAI is a tool designed to assist healthcare professionals
                in capturing and managing medical information based on inputs
                collected during consultations and medical briefings. While
                MedSightAI strives to facilitate accurate and efficient data
                management, it is imperative to note that the responsibility for
                validating and recording medical information into any medical
                records system rests solely with the healthcare professional
                using the application.
              </Text>
              <Text style={styles.cardContent}>
                Accuracy and Validation: Healthcare professionals are obligated
                to verify the accuracy, completeness, and applicability of all
                data collected and generated by MedSightAI. Users must exercise
                professional judgment to review and confirm all information
                before incorporation into a patient’s medical record.
              </Text>
              <Text style={styles.cardContent}>
                Limitation of Liability: MedSightAI does not assume liability
                for inaccuracies, errors, or omissions in the information
                captured by MedSightAI. Nor are we responsible for any decisions
                or actions taken by healthcare professionals based on the data
                provided by the application.
              </Text>
            </View>
          </ScrollView>
        </View>
      </ImageBackground>
    </SafeAreaView>
  );
};

export default Legal;

// Styles
const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollContainer: {
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  iconContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    marginTop: 20,
  },
  icon: {
    width: 24,
    height: 24,
    resizeMode: 'contain',
    marginRight: 10,
    alignItems: 'center',
  },
  title: {
    fontSize: 18,
    fontWeight: '700',
    color: '#333',
  },
  card: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#000000',
    marginBottom: 10,
  },
  cardContent: {
    fontSize: 14,
    fontWeight: '400',
    color: '#000000',
    lineHeight: 20,
    marginBottom: 10,
  },
});
